### ISSUE TITLE
Win UI 3.0 project setup in VS 2019 is no longer correct in the book

### ISSUE THREAD

**Issue by asouth** [PacktPublishing/-Learn-WinUI-3.0#4]
Chapter 2 requires updating and including in the errata as it is not clear how to replicate the steps in the book for setting up a Win UI 3.0 project.  

This is because the "WinUI Project Templates" in NuGet Manager now shows as depreciated. Yet the option to select "WinUI in UWP" does not yet exist in the latest version of VS Community 2019 Version 16.11.0 (fully update to as of today). 

Therefore what is the "correct way" to setup a blank "WinUI 3.0 in UWP" project.

There is information [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?tabs=uwp) and i have installed the " Windows App SDK Experimental Extension for Visual Studio" as suggested, however the resulting project created using the experimental template does not contain any reference to Microsoft.WinUI as referred to in the book on page 45 "Reviewing project References" 

Note that "WinUI in Desktop" does exist as a project template.

**Comment by alvinashcraft** [comment]
Microsoft made changes so that the UWP features of WinUI are only available in the Experimental Channel of the WindowsAppSDK. I'm on vacation until after the U.S. Labor Day holiday, but you can read more about how to use features in the Experimental Channel [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel).

**Comment by SteveF4** [comment]
Thank-you! On 2021-09-09, I downloaded and installed Windows App SDK "Version 1.0 Experimental" from https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#version-10-experimental-100-experimental1, started VS 2019, and found "[Experimental] Blank App (WinUI 3 in UWP)" in the "Create a new project" list. Onward!
